using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using CommDetect.Core;
using Microsoft.Extensions.Logging;

namespace CommDetect.IO;

/// <summary>
/// Unified commercial processor — the Comcut + Comchap replacement.
/// Chains detection results into one of several processing modes:
///   skip    → EDL/marker files only (non-destructive)
///   chapter → Embed chapter markers into the container
///   cut     → Remove commercials and produce a clean file
///   both    → Chapter + Cut
///
/// All behavior is driven by comprocess.ini settings, giving users full
/// control over FFmpeg encoding, container format, and file handling.
/// </summary>
public class CommercialProcessor
{
    private readonly IFFmpegLocator _ffmpegLocator;
    private readonly ILogger<CommercialProcessor>? _logger;

    public CommercialProcessor(
        IFFmpegLocator ffmpegLocator,
        ILogger<CommercialProcessor>? logger = null)
    {
        _ffmpegLocator = ffmpegLocator;
        _logger = logger;
    }

    /// <summary>
    /// Process a file according to the processing config.
    /// Assumes commercial detection has already been run and an AnalysisResult is provided.
    /// </summary>
    public async Task<ProcessingResult> ProcessAsync(
        AnalysisResult analysisResult,
        ProcessingConfig config,
        CancellationToken cancellationToken = default)
    {
        var result = new ProcessingResult
        {
            SourceFile = analysisResult.SourceFile,
            Mode = config.Mode,
            StartedUtc = DateTime.UtcNow
        };

        string ffmpegPath = !string.IsNullOrEmpty(config.FFmpegPath)
            ? config.FFmpegPath
            : _ffmpegLocator.FindFFmpeg()
              ?? throw new InvalidOperationException("FFmpeg not found.");

        var cmdBuilder = new FFmpegCommandBuilder(config, ffmpegPath);

        var programSegments = analysisResult.Segments
            .Where(s => s.Type == SegmentType.Program)
            .OrderBy(s => s.Start)
            .ToList();

        var commercialSegments = analysisResult.Segments
            .Where(s => s.Type == SegmentType.Commercial)
            .OrderBy(s => s.Start)
            .ToList();

        _logger?.LogInformation(
            "Processing {File}: mode={Mode}, {CommCount} commercials, {ProgCount} program segments",
            Path.GetFileName(analysisResult.SourceFile),
            config.Mode,
            commercialSegments.Count,
            programSegments.Count);

        try
        {
            switch (config.Mode)
            {
                case ProcessingMode.Skip:
                    // EDL/markers already generated by the detection pipeline
                    result.OutputFiles.Add(analysisResult.SourceFile);
                    _logger?.LogInformation("Skip mode — marker files already generated");
                    break;

                case ProcessingMode.Chapter:
                    await ProcessChapterAsync(
                        analysisResult, config, cmdBuilder, ffmpegPath, result, cancellationToken);
                    break;

                case ProcessingMode.Cut:
                    await ProcessCutAsync(
                        analysisResult, programSegments, config, cmdBuilder, ffmpegPath, result, cancellationToken);
                    break;

                case ProcessingMode.Both:
                    await ProcessChapterAsync(
                        analysisResult, config, cmdBuilder, ffmpegPath, result, cancellationToken);
                    await ProcessCutAsync(
                        analysisResult, programSegments, config, cmdBuilder, ffmpegPath, result, cancellationToken);
                    break;
            }

            // Handle the original file
            if (config.Mode != ProcessingMode.Skip && result.Success)
            {
                await HandleOriginalFileAsync(analysisResult.SourceFile, config);
            }

            result.Success = true;
            result.CompletedUtc = DateTime.UtcNow;

            double removedSeconds = commercialSegments.Sum(s => s.DurationSeconds);
            _logger?.LogInformation(
                "Processing complete: {Mode} mode, {Removed:F0}s of commercials processed, took {Elapsed:F1}s",
                config.Mode, removedSeconds, result.Duration.TotalSeconds);
        }
        catch (Exception ex)
        {
            result.Success = false;
            result.ErrorMessage = ex.Message;
            result.CompletedUtc = DateTime.UtcNow;
            _logger?.LogError(ex, "Processing failed for {File}", analysisResult.SourceFile);
        }

        return result;
    }

    // ── Chapter Processing ──────────────────────────────────────────────

    private async Task ProcessChapterAsync(
        AnalysisResult analysis,
        ProcessingConfig config,
        FFmpegCommandBuilder cmdBuilder,
        string ffmpegPath,
        ProcessingResult result,
        CancellationToken ct)
    {
        _logger?.LogInformation("Embedding chapter markers...");

        string inputPath = analysis.SourceFile;
        string outputExt = cmdBuilder.GetOutputExtension(inputPath);
        string outputPath = Path.ChangeExtension(
            cmdBuilder.BuildOutputPath(inputPath), outputExt);

        // Generate FFmetadata chapter file
        string metadataPath = Path.Combine(
            GetTempDir(config),
            Path.GetFileNameWithoutExtension(inputPath) + ".ffmeta");

        await WriteFFMetadataChaptersAsync(analysis, config, metadataPath, ct);

        // Determine tool to use
        string tool = config.ChapterTool.ToLowerInvariant();
        bool useMkvmerge = tool == "mkvmerge" ||
                           (tool == "auto" && outputExt.Equals(".mkv", StringComparison.OrdinalIgnoreCase));

        if (useMkvmerge && !string.IsNullOrEmpty(FindMkvmerge(config)))
        {
            await EmbedChaptersWithMkvmergeAsync(
                inputPath, outputPath, analysis, config, ct);
        }
        else
        {
            // Use FFmpeg
            string args = cmdBuilder.BuildChapterEmbedArgs(inputPath, metadataPath, outputPath);
            await RunFFmpegAsync(ffmpegPath, args, config, ct);
        }

        result.OutputFiles.Add(outputPath);

        // Cleanup temp
        if (!config.KeepTempFiles && File.Exists(metadataPath))
            File.Delete(metadataPath);
    }

    private async Task WriteFFMetadataChaptersAsync(
        AnalysisResult analysis, ProcessingConfig config,
        string outputPath, CancellationToken ct)
    {
        var sb = new StringBuilder();
        sb.AppendLine(";FFMETADATA1");

        int programNum = 1;
        int commercialNum = 1;

        foreach (var segment in analysis.Segments.OrderBy(s => s.Start))
        {
            long startMs = (long)segment.Start.TotalMilliseconds;
            long endMs = (long)segment.End.TotalMilliseconds;

            string title;
            if (segment.Type == SegmentType.Commercial)
            {
                title = config.CommercialChapterLabel.Replace("{number}", commercialNum.ToString());
                commercialNum++;
            }
            else
            {
                title = config.ProgramChapterLabel.Replace("{number}", programNum.ToString());
                programNum++;
            }

            sb.AppendLine("[CHAPTER]");
            sb.AppendLine("TIMEBASE=1/1000");
            sb.AppendLine($"START={startMs}");
            sb.AppendLine($"END={endMs}");
            sb.AppendLine($"title={title}");
        }

        await File.WriteAllTextAsync(outputPath, sb.ToString(), ct);
    }

    private async Task EmbedChaptersWithMkvmergeAsync(
        string inputPath, string outputPath,
        AnalysisResult analysis, ProcessingConfig config,
        CancellationToken ct)
    {
        string? mkvmerge = FindMkvmerge(config);
        if (mkvmerge == null)
            throw new InvalidOperationException("mkvmerge not found. Install mkvtoolnix.");

        // Write MKV chapter XML
        string chapterXml = Path.Combine(
            GetTempDir(config),
            Path.GetFileNameWithoutExtension(inputPath) + ".chapters.xml");

        await WriteMkvChapterXmlAsync(analysis, config, chapterXml, ct);

        string args = $"-o \"{outputPath}\" --chapters \"{chapterXml}\" \"{inputPath}\"";

        _logger?.LogDebug("Running: {Mkvmerge} {Args}", mkvmerge, args);

        var (exitCode, _) = await RunProcessAsync(mkvmerge, args, config, ct);
        if (exitCode != 0 && exitCode != 1) // mkvmerge returns 1 for warnings
            throw new InvalidOperationException($"mkvmerge failed with exit code {exitCode}");

        if (!config.KeepTempFiles && File.Exists(chapterXml))
            File.Delete(chapterXml);
    }

    private async Task WriteMkvChapterXmlAsync(
        AnalysisResult analysis, ProcessingConfig config,
        string outputPath, CancellationToken ct)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
        sb.AppendLine("<Chapters>");
        sb.AppendLine("  <EditionEntry>");

        if (config.SetDefaultEdition)
            sb.AppendLine("    <EditionFlagDefault>1</EditionFlagDefault>");

        int programNum = 1;
        int commercialNum = 1;

        foreach (var segment in analysis.Segments.OrderBy(s => s.Start))
        {
            string title;
            bool hidden = false;

            if (segment.Type == SegmentType.Commercial)
            {
                title = config.CommercialChapterLabel.Replace("{number}", commercialNum.ToString());
                hidden = config.HideCommercialChapters;
                commercialNum++;
            }
            else
            {
                title = config.ProgramChapterLabel.Replace("{number}", programNum.ToString());
                programNum++;
            }

            sb.AppendLine("    <ChapterAtom>");
            sb.AppendLine($"      <ChapterTimeStart>{FormatMkvTime(segment.Start)}</ChapterTimeStart>");
            sb.AppendLine($"      <ChapterTimeEnd>{FormatMkvTime(segment.End)}</ChapterTimeEnd>");
            if (hidden) sb.AppendLine("      <ChapterFlagHidden>1</ChapterFlagHidden>");
            sb.AppendLine("      <ChapterDisplay>");
            sb.AppendLine($"        <ChapterString>{title}</ChapterString>");
            sb.AppendLine("        <ChapLanguageIETF>en</ChapLanguageIETF>");
            sb.AppendLine("      </ChapterDisplay>");
            sb.AppendLine("    </ChapterAtom>");
        }

        sb.AppendLine("  </EditionEntry>");
        sb.AppendLine("</Chapters>");

        await File.WriteAllTextAsync(outputPath, sb.ToString(), ct);
    }

    // ── Cut Processing ──────────────────────────────────────────────────

    private async Task ProcessCutAsync(
        AnalysisResult analysis,
        List<ContentSegment> programSegments,
        ProcessingConfig config,
        FFmpegCommandBuilder cmdBuilder,
        string ffmpegPath,
        ProcessingResult result,
        CancellationToken ct)
    {
        _logger?.LogInformation("Cutting commercials (method: {Method})...", config.CutMethod);

        string inputPath = analysis.SourceFile;
        string outputPath = cmdBuilder.BuildOutputPath(inputPath);

        // Ensure we don't overwrite the input
        if (Path.GetFullPath(outputPath).Equals(Path.GetFullPath(inputPath), StringComparison.OrdinalIgnoreCase))
        {
            string ext = cmdBuilder.GetOutputExtension(inputPath);
            outputPath = Path.Combine(
                Path.GetDirectoryName(inputPath) ?? ".",
                Path.GetFileNameWithoutExtension(inputPath) + ".cut" + ext);
        }

        if (!config.OverwriteExisting && File.Exists(outputPath))
        {
            _logger?.LogWarning("Output file already exists, skipping: {Path}", outputPath);
            result.OutputFiles.Add(outputPath);
            return;
        }

        switch (config.CutMethod)
        {
            case CutMethod.Concat:
                await CutWithConcatAsync(
                    inputPath, outputPath, programSegments, config, cmdBuilder, ffmpegPath, ct);
                break;

            case CutMethod.Smart:
                await CutWithSmartReencodeAsync(
                    inputPath, outputPath, programSegments, config, cmdBuilder, ffmpegPath, ct);
                break;

            case CutMethod.Reencode:
                string args = cmdBuilder.BuildReencodeArgs(inputPath, outputPath, programSegments);
                await RunFFmpegAsync(ffmpegPath, args, config, ct);
                break;
        }

        result.OutputFiles.Add(outputPath);

        // Report size savings
        if (File.Exists(outputPath))
        {
            long originalSize = new FileInfo(inputPath).Length;
            long newSize = new FileInfo(outputPath).Length;
            double savingsPercent = (1.0 - (double)newSize / originalSize) * 100;
            _logger?.LogInformation(
                "Size: {Original:F1}MB → {New:F1}MB ({Savings:F1}% reduction)",
                originalSize / (1024.0 * 1024.0),
                newSize / (1024.0 * 1024.0),
                savingsPercent);
        }
    }

    private async Task CutWithConcatAsync(
        string inputPath, string outputPath,
        List<ContentSegment> programSegments,
        ProcessingConfig config,
        FFmpegCommandBuilder cmdBuilder,
        string ffmpegPath,
        CancellationToken ct)
    {
        string tempDir = GetTempDir(config);
        var segmentFiles = new List<string>();

        // Re-encode each segment if the target format differs from the source, or if explicit
        // codec settings are configured — then concatenate the identically-encoded pieces.
        // This avoids a single massive filter_complex and is safe for any file length.
        bool needsReencode = config.ContainerFormat != ContainerFormat.Original
                          || config.VideoCodec != "copy"
                          || config.AudioCodec != "copy";

        string segExt = needsReencode
            ? cmdBuilder.GetOutputExtension(inputPath)
            : Path.GetExtension(inputPath);

        try
        {
            // Extract (and optionally re-encode) each program segment
            for (int i = 0; i < programSegments.Count; i++)
            {
                var seg = programSegments[i];
                string segPath = Path.Combine(tempDir,
                    $"{Path.GetFileNameWithoutExtension(inputPath)}_seg{i:D3}{segExt}");

                var duration = seg.End - seg.Start;
                string args = needsReencode
                    ? cmdBuilder.BuildSegmentEncodeArgs(inputPath, segPath, seg.Start, duration)
                    : cmdBuilder.BuildSegmentExtractArgs(inputPath, segPath, seg.Start, duration);

                await RunFFmpegAsync(ffmpegPath, args, config, ct);

                segmentFiles.Add(segPath);
                _logger?.LogDebug("Extracted segment {Idx}: {Start} → {End}", i, seg.Start, seg.End);
            }

            // Write concat file list
            string concatList = Path.Combine(tempDir, "concat_list.txt");
            var lines = segmentFiles.Select(f => $"file '{f.Replace("'", "'\\''")}'");
            await File.WriteAllLinesAsync(concatList, lines, ct);

            // Concatenate all segments
            string concatArgs = cmdBuilder.BuildConcatArgs(concatList, outputPath);
            await RunFFmpegAsync(ffmpegPath, concatArgs, config, ct);
        }
        finally
        {
            // Cleanup temp segment files
            if (!config.KeepTempFiles)
            {
                foreach (var f in segmentFiles)
                    if (File.Exists(f)) File.Delete(f);

                string concatList = Path.Combine(tempDir, "concat_list.txt");
                if (File.Exists(concatList)) File.Delete(concatList);
            }
        }
    }

    private async Task CutWithSmartReencodeAsync(
        string inputPath, string outputPath,
        List<ContentSegment> programSegments,
        ProcessingConfig config,
        FFmpegCommandBuilder cmdBuilder,
        string ffmpegPath,
        CancellationToken ct)
    {
        // Smart cut: re-encode a margin around each cut point, stream-copy the rest.
        // For simplicity in the initial implementation, we use the re-encode path
        // with the full filter graph. A production version would optimize this further
        // by doing per-segment stream-copy with re-encode only at boundaries.

        var segments = programSegments.Select(seg => (
            start: seg.Start,
            end: seg.End,
            needsReencode: true // In a full implementation, only edges would be true
        )).ToList();

        string args = cmdBuilder.BuildSmartCutArgs(inputPath, outputPath, segments);
        await RunFFmpegAsync(ffmpegPath, args, config, ct);
    }

    // ── Original File Handling ──────────────────────────────────────────

    private async Task HandleOriginalFileAsync(string originalPath, ProcessingConfig config)
    {
        switch (config.OriginalAction)
        {
            case OriginalAction.Delete:
                _logger?.LogInformation("Deleting original: {Path}", originalPath);
                File.Delete(originalPath);
                break;

            case OriginalAction.Move:
                string archiveDir = config.OriginalArchiveDir
                    .Replace("{date}", DateTime.Now.ToString("yyyy-MM-dd"));

                if (!Directory.Exists(archiveDir))
                    Directory.CreateDirectory(archiveDir);

                string destPath = Path.Combine(archiveDir, Path.GetFileName(originalPath));
                _logger?.LogInformation("Moving original to: {Path}", destPath);
                File.Move(originalPath, destPath, overwrite: false);
                break;

            case OriginalAction.Keep:
            default:
                // Do nothing
                break;
        }

        await Task.CompletedTask;
    }

    // ── Helpers ──────────────────────────────────────────────────────────

    private async Task RunFFmpegAsync(
        string ffmpegPath, string args, ProcessingConfig config, CancellationToken ct)
    {
        _logger?.LogDebug("Running: {FFmpeg} {Args}", ffmpegPath, args);

        var (exitCode, stderr) = await RunProcessAsync(ffmpegPath, args, config, ct);

        if (exitCode != 0)
        {
            if (!string.IsNullOrEmpty(stderr))
                _logger?.LogError("FFmpeg stderr:\n{Stderr}", stderr);
            // Include the last meaningful line of stderr in the exception so it appears
            // in the console output even without --verbose.
            string detail = string.IsNullOrEmpty(stderr)
                ? ""
                : ": " + (stderr.Trim().Split('\n').LastOrDefault(l => !string.IsNullOrWhiteSpace(l)) ?? "");
            throw new InvalidOperationException($"FFmpeg failed with exit code {exitCode}{detail}");
        }
    }

    private async Task<(int exitCode, string stderr)> RunProcessAsync(
        string executable, string args, ProcessingConfig config, CancellationToken ct)
    {
        var psi = new ProcessStartInfo
        {
            FileName = executable,
            Arguments = args,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };

        using var process = Process.Start(psi)
            ?? throw new InvalidOperationException($"Failed to start {executable}");

        // Set process priority
        try
        {
            process.PriorityClass = config.ProcessPriority.ToLowerInvariant() switch
            {
                "idle" => ProcessPriorityClass.Idle,
                "below_normal" or "belownormal" => ProcessPriorityClass.BelowNormal,
                _ => ProcessPriorityClass.Normal
            };
        }
        catch { /* May not have permission to change priority */ }

        // Drain stdout/stderr asynchronously — CRITICAL: not reading these pipes causes the
        // process to block when the OS pipe buffer fills up (typically ~64 KB), which eventually
        // triggers the cancellation token and surfaces as TaskCanceledException.
        var stdoutDrain = process.StandardOutput.ReadToEndAsync();
        var stderrTask  = process.StandardError.ReadToEndAsync();

        try
        {
            // Handle timeout
            if (config.ProcessingTimeoutMinutes > 0)
            {
                using var timeoutCts = CancellationTokenSource.CreateLinkedTokenSource(ct);
                timeoutCts.CancelAfter(TimeSpan.FromMinutes(config.ProcessingTimeoutMinutes));

                try
                {
                    await process.WaitForExitAsync(timeoutCts.Token);
                }
                catch (OperationCanceledException) when (!ct.IsCancellationRequested)
                {
                    process.Kill(entireProcessTree: true);
                    throw new TimeoutException(
                        $"Processing timed out after {config.ProcessingTimeoutMinutes} minutes");
                }
            }
            else
            {
                await process.WaitForExitAsync(ct);
            }
        }
        catch when (ct.IsCancellationRequested)
        {
            try { process.Kill(entireProcessTree: true); } catch { /* already exited */ }
            throw;
        }

        // Collect stderr output for diagnostics
        string stderr = await stderrTask;
        await stdoutDrain;

        return (process.ExitCode, stderr);
    }

    private string? FindMkvmerge(ProcessingConfig config)
    {
        if (!string.IsNullOrEmpty(config.MkvmergePath) && File.Exists(config.MkvmergePath))
            return config.MkvmergePath;

        string name = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? "mkvmerge.exe" : "mkvmerge";

        // Check PATH
        string? pathVar = Environment.GetEnvironmentVariable("PATH");
        if (pathVar != null)
        {
            char sep = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? ';' : ':';
            foreach (var dir in pathVar.Split(sep, StringSplitOptions.RemoveEmptyEntries))
            {
                string candidate = Path.Combine(dir.Trim(), name);
                if (File.Exists(candidate)) return candidate;
            }
        }

        // Common locations
        var locations = new[]
        {
            "/usr/bin/mkvmerge",
            "/usr/local/bin/mkvmerge",
            @"C:\Program Files\MKVToolNix\mkvmerge.exe"
        };

        return locations.FirstOrDefault(File.Exists);
    }

    private string GetTempDir(ProcessingConfig config)
    {
        string tempDir = !string.IsNullOrEmpty(config.TempDir) ? config.TempDir : Path.GetTempPath();
        string commdetectTemp = Path.Combine(tempDir, "commdetect");
        if (!Directory.Exists(commdetectTemp))
            Directory.CreateDirectory(commdetectTemp);
        return commdetectTemp;
    }

    private static string FormatMkvTime(TimeSpan ts) =>
        $"{(int)ts.TotalHours:D2}:{ts.Minutes:D2}:{ts.Seconds:D2}.{ts.Milliseconds:D3}000000";
}

/// <summary>
/// Result of a processing operation.
/// </summary>
public class ProcessingResult
{
    public string SourceFile { get; set; } = "";
    public ProcessingMode Mode { get; set; }
    public bool Success { get; set; }
    public string? ErrorMessage { get; set; }
    public List<string> OutputFiles { get; set; } = new();
    public DateTime StartedUtc { get; set; }
    public DateTime CompletedUtc { get; set; }
    public TimeSpan Duration => CompletedUtc - StartedUtc;
}
