using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using MediaBrowser.Common.Configuration;
using MediaBrowser.Common.Plugins;
using MediaBrowser.Model.Drawing;
using MediaBrowser.Model.Plugins;
using MediaBrowser.Model.Serialization;

namespace CommDetect.EmbyPlugin;

/// <summary>
/// CommDetect — Commercial Detection and Processing plugin for Emby.
/// Provides a configuration UI for all commdetect.ini and comprocess.ini settings.
/// Writes updated ini files to the commdetect binary directory when settings are saved.
/// </summary>
public class Plugin : BasePlugin<PluginConfiguration>, IHasWebPages, IHasThumbImage
{
    public static Plugin? Instance { get; private set; }

    public Plugin(IApplicationPaths applicationPaths, IXmlSerializer xmlSerializer)
        : base(applicationPaths, xmlSerializer)
    {
        Instance = this;
    }

    public override string Name => "CommDetect - Commercial Detection and Processing";
    public override string Description => "Detects and removes commercial breaks from Live TV recordings using multi-signal analysis.";
    public override Guid Id => new Guid("7c4e8f3a-2d51-4b69-9c87-0f3e2a1d5b6c");

    // ── Web pages ─────────────────────────────────────────────────────────────

    public IEnumerable<PluginPageInfo> GetPages() => new[]
    {
        new PluginPageInfo
        {
            Name = "CommDetect",
            EmbeddedResourcePath = "CommDetect.EmbyPlugin.Configuration.configPage.html"
        }
    };

    // ── Thumb image ───────────────────────────────────────────────────────────

    public ImageFormat ThumbImageFormat => ImageFormat.Png;

    public Stream GetThumbImage()
    {
        var type = GetType();
        return type.Assembly.GetManifestResourceStream("CommDetect.EmbyPlugin.Images.thumb.png")
               ?? Stream.Null;
    }

    // ── Configuration save hook ───────────────────────────────────────────────

    public override void SaveConfiguration()
    {
        base.SaveConfiguration();
        try
        {
            WriteIniFiles(Configuration);
        }
        catch
        {
            // Non-fatal — Emby config is saved regardless; ini write failure
            // is logged but does not prevent the plugin from functioning.
        }
    }

    // ── Ini file writers ──────────────────────────────────────────────────────

    private static void WriteIniFiles(PluginConfiguration cfg)
    {
        if (string.IsNullOrWhiteSpace(cfg.CommdetectBinaryPath))
            return;

        var dir = Path.GetDirectoryName(cfg.CommdetectBinaryPath);
        if (string.IsNullOrEmpty(dir))
            return;

        File.WriteAllText(Path.Combine(dir, "commdetect.ini"), BuildCommdetectIni(cfg), Encoding.UTF8);
        File.WriteAllText(Path.Combine(dir, "comprocess.ini"), BuildComprocessIni(cfg), Encoding.UTF8);
    }

    private static string BuildCommdetectIni(PluginConfiguration c)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# CommDetect — Commercial Detection Configuration");
        sb.AppendLine("# Generated by the CommDetect Emby plugin. Edit via Emby Dashboard → Plugins → CommDetect.");
        sb.AppendLine();

        sb.AppendLine("[General]");
        sb.AppendLine($"preset={c.Preset}");
        sb.AppendLine($"window_size={c.WindowSize}");
        sb.AppendLine($"frame_sample_rate={c.FrameSampleRate}");
        sb.AppendLine($"max_parallelism={c.MaxParallelism}");
        sb.AppendLine();

        sb.AppendLine("[Detection]");
        sb.AppendLine($"commercial_threshold={c.CommercialThreshold}");
        sb.AppendLine($"smoothing_radius={c.SmoothingRadius}");
        sb.AppendLine($"skip_start_seconds={c.SkipStartSeconds}");
        sb.AppendLine($"skip_end_seconds={c.SkipEndSeconds}");
        sb.AppendLine($"min_commercial_seconds={c.MinCommercialSeconds}");
        sb.AppendLine($"max_commercial_seconds={c.MaxCommercialSeconds}");
        sb.AppendLine($"padding_seconds={c.PaddingSeconds}");
        sb.AppendLine();

        sb.AppendLine("[BlackFrame]");
        sb.AppendLine($"enabled={c.BlackFrameEnabled.ToString().ToLower()}");
        sb.AppendLine($"luma_threshold={c.BlackFrameLumaThreshold}");
        sb.AppendLine($"min_count={c.BlackFrameMinCount}");
        sb.AppendLine($"weight={c.BlackFrameWeight}");
        sb.AppendLine($"use_clustering={c.BlackFrameUseClustering.ToString().ToLower()}");
        sb.AppendLine($"cluster_max_gap={c.BlackFrameClusterMaxGap}");
        sb.AppendLine($"cluster_min_duration={c.BlackFrameClusterMinDuration}");
        sb.AppendLine($"cluster_min_events={c.BlackFrameClusterMinEvents}");
        sb.AppendLine();

        sb.AppendLine("[SceneChange]");
        sb.AppendLine($"enabled={c.SceneChangeEnabled.ToString().ToLower()}");
        sb.AppendLine($"threshold={c.SceneChangeThreshold}");
        sb.AppendLine($"rate_threshold={c.SceneChangeRateThreshold}");
        sb.AppendLine($"weight={c.SceneChangeWeight}");
        sb.AppendLine();

        sb.AppendLine("[Silence]");
        sb.AppendLine($"enabled={c.SilenceEnabled.ToString().ToLower()}");
        sb.AppendLine($"rms_threshold={c.SilenceRmsThreshold}");
        sb.AppendLine($"min_duration={c.SilenceMinDuration}");
        sb.AppendLine($"weight={c.SilenceWeight}");
        sb.AppendLine();

        sb.AppendLine("[Logo]");
        sb.AppendLine($"enabled={c.LogoEnabled.ToString().ToLower()}");
        sb.AppendLine($"learn_duration={c.LogoLearnDuration}");
        sb.AppendLine($"cluster_min_events={c.LogoClusterMinEvents}");
        sb.AppendLine($"weight={c.LogoWeight}");
        sb.AppendLine($"logo_ssim_threshold={c.LogoSsimThreshold}");
        sb.AppendLine($"logo_corner_filter_ratio={c.LogoCornerFilterRatio}");
        sb.AppendLine();

        sb.AppendLine("[Letterbox]");
        sb.AppendLine($"enabled={c.LetterboxEnabled.ToString().ToLower()}");
        sb.AppendLine($"weight={c.LetterboxWeight}");
        sb.AppendLine($"min_duration={c.LetterboxMinDuration}");
        sb.AppendLine($"pic_threshold={c.LetterboxPicThreshold}");
        sb.AppendLine();

        sb.AppendLine("[AspectRatio]");
        sb.AppendLine($"enabled={c.AspectRatioEnabled.ToString().ToLower()}");
        sb.AppendLine($"weight={c.AspectRatioWeight}");
        sb.AppendLine();

        sb.AppendLine("[AudioFingerprint]");
        sb.AppendLine($"enabled={c.AudioFingerprintEnabled.ToString().ToLower()}");
        sb.AppendLine($"min_repetitions={c.AudioFingerprintMinRepetitions}");
        sb.AppendLine($"weight={c.AudioFingerprintWeight}");
        sb.AppendLine();

        sb.AppendLine("[Emby]");
        sb.AppendLine($"server_url={c.EmbyServerUrl}");
        sb.AppendLine($"api_key={c.EmbyApiKey}");
        sb.AppendLine();

        sb.AppendLine("[Psip]");
        sb.AppendLine($"enabled={c.PsipEnabled.ToString().ToLower()}");
        sb.AppendLine();

        sb.AppendLine("[Xds]");
        sb.AppendLine($"enabled={c.XdsEnabled.ToString().ToLower()}");
        sb.AppendLine();

        sb.AppendLine("[Logging]");
        sb.AppendLine($"enabled={c.LoggingEnabled.ToString().ToLower()}");
        sb.AppendLine($"log_dir={c.LogDir}");
        sb.AppendLine($"edl_dir={c.EdlDir}");
        sb.AppendLine($"retention_days={c.RetentionDays}");
        sb.AppendLine($"video_dir={c.VideoDir}");
        sb.AppendLine();

        sb.AppendLine("[Output]");
        sb.AppendLine($"formats={c.OutputFormats}");
        sb.AppendLine($"output_location={c.OutputLocation}");
        sb.AppendLine();

        sb.AppendLine("[Watch]");
        sb.AppendLine($"stability_delay={c.WatchStabilityDelay}");
        sb.AppendLine($"min_file_size_mb={c.WatchMinFileSizeMb}");
        sb.AppendLine($"skip_already_processed={c.WatchSkipAlreadyProcessed.ToString().ToLower()}");
        sb.AppendLine($"max_concurrent_jobs={c.WatchMaxConcurrentJobs}");
        sb.AppendLine($"file_extensions={c.WatchFileExtensions}");
        sb.AppendLine($"exclude_patterns={c.WatchExcludePatterns}");
        sb.AppendLine($"process_existing_on_startup={c.WatchProcessExistingOnStartup.ToString().ToLower()}");

        return sb.ToString();
    }

    private static string BuildComprocessIni(PluginConfiguration c)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# ComProcess — Commercial Processing Configuration");
        sb.AppendLine("# Generated by the CommDetect Emby plugin. Edit via Emby Dashboard → Plugins → CommDetect.");
        sb.AppendLine();

        sb.AppendLine("[General]");
        sb.AppendLine($"mode={c.ProcessingMode}");
        sb.AppendLine($"original_action={c.OriginalAction}");
        sb.AppendLine($"original_archive_dir={c.OriginalArchiveDir}");
        sb.AppendLine($"output_name_pattern={c.OutputNamePattern}");
        sb.AppendLine($"overwrite_existing={c.OverwriteExisting.ToString().ToLower()}");
        sb.AppendLine();

        sb.AppendLine("[Container]");
        sb.AppendLine($"format={c.ContainerFormat}");
        sb.AppendLine($"remux_only={c.RemuxOnly.ToString().ToLower()}");
        sb.AppendLine();

        sb.AppendLine("[ChapterMarking]");
        sb.AppendLine($"program_chapter_label={c.ProgramChapterLabel}");
        sb.AppendLine($"commercial_chapter_label={c.CommercialChapterLabel}");
        sb.AppendLine($"hide_commercial_chapters={c.HideCommercialChapters.ToString().ToLower()}");
        sb.AppendLine($"set_default_edition={c.SetDefaultEdition.ToString().ToLower()}");
        sb.AppendLine($"chapter_tool={c.ChapterTool}");
        sb.AppendLine();

        sb.AppendLine("[Cut]");
        sb.AppendLine($"cut_method={c.CutMethod}");
        sb.AppendLine($"smart_reencode_margin={c.SmartReencodemargin}");
        sb.AppendLine($"fade_at_cuts={c.FadeAtCuts.ToString().ToLower()}");
        sb.AppendLine($"fade_duration={c.FadeDuration}");
        sb.AppendLine();

        sb.AppendLine("[VideoEncode]");
        sb.AppendLine($"codec={c.VideoCodec}");
        sb.AppendLine($"preset={c.VideoPreset}");
        sb.AppendLine($"crf={c.VideoCrf}");
        sb.AppendLine($"resolution={c.VideoResolution}");
        sb.AppendLine($"pixel_format={c.VideoPixelFormat}");
        sb.AppendLine($"hw_accel={c.VideoHwAccel}");
        sb.AppendLine($"deinterlace={c.VideoDeinterlace}");
        sb.AppendLine($"extra_filters={c.VideoExtraFilters}");
        sb.AppendLine($"extra_args={c.VideoExtraArgs}");
        sb.AppendLine();

        sb.AppendLine("[AudioEncode]");
        sb.AppendLine($"codec={c.AudioCodec}");
        sb.AppendLine($"bitrate={c.AudioBitrate}");
        sb.AppendLine($"sample_rate={c.AudioSampleRate}");
        sb.AppendLine($"channels={c.AudioChannels}");
        sb.AppendLine($"normalize={c.AudioNormalize.ToString().ToLower()}");
        sb.AppendLine($"normalize_target={c.AudioNormalizeTarget}");
        sb.AppendLine();

        sb.AppendLine("[SubtitleHandling]");
        sb.AppendLine($"copy_subtitles={c.CopySubtitles}");
        sb.AppendLine($"preferred_languages={c.PreferredLanguages}");
        sb.AppendLine($"adjust_timing={c.AdjustTiming.ToString().ToLower()}");
        sb.AppendLine();

        sb.AppendLine("[Metadata]");
        sb.AppendLine($"copy_metadata={c.CopyMetadata.ToString().ToLower()}");
        sb.AppendLine($"add_processing_info={c.AddProcessingInfo.ToString().ToLower()}");
        sb.AppendLine($"custom_metadata={c.CustomMetadata}");
        sb.AppendLine();

        sb.AppendLine("[Advanced]");
        sb.AppendLine($"ffmpeg_path={c.FfmpegPath}");
        sb.AppendLine($"ffprobe_path={c.FfprobePath}");
        sb.AppendLine($"mkvmerge_path={c.MkvmergePath}");
        sb.AppendLine($"temp_dir={c.TempDir}");
        sb.AppendLine($"keep_temp_files={c.KeepTempFiles.ToString().ToLower()}");
        sb.AppendLine($"process_priority={c.ProcessPriority}");
        sb.AppendLine($"ffmpeg_log_level={c.FfmpegLogLevel}");
        sb.AppendLine($"processing_timeout_minutes={c.ProcessingTimeoutMinutes}");

        return sb.ToString();
    }
}
